export const TagsDescription = {
  Array: 1,
  Backtracking: 0,
  "Binary Indexed Tree": 0,
  "Binary Search": 0,
  "Bit Manipulation": 0,
  "Breadth-First Search": 0,
  Design: 0,
  "Depth-First Search": 0,
  "Divide and Conquer": 0,
  "Dynamic Programming": 0,
  "Game Theory": 0,
  Graph: 0,
  Greedy: 0,
  "Hash Function": 0,
  "Hash Table": 0,
  "Heap (Priority Queue)": 0,
  "Linked List": 0,
  Math: 0,
  Memoization: 0,
  "Monotonic Stack": 0,
  Queue: 0,
  Recursion: 0,
  "Segment Tree": 0,
  "Sliding Window": 0,
  Sort: 0,
  Stack: 0,
  String: 0,
  Tree: 0,
  Trie: 0,
  "Two Pointers": 0,
  "Union Find": 0,
};
